import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SubNav from "@/components/SubNav";
import { cn } from "@/lib/utils";
import Nav from "@/components/Nav";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: " E-commerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn`${geistSans.variable} ${geistMono.variable} antialiased`}
            >

                <SubNav />
                <Nav />

                {children}
            </body>
        </html>
    );
}
